/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterLevelRouteImport } from './routes/water-level'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as BaseControlRouteImport } from './routes/base-control'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DataVitalsRouteImport } from './routes/data/vitals'
import { Route as DataSleepRouteImport } from './routes/data/sleep'
import { Route as DataLogsRouteImport } from './routes/data/logs'

const WaterLevelRoute = WaterLevelRouteImport.update({
  id: '/water-level',
  path: '/water-level',
  getParentRoute: () => rootRouteImport,
} as any)
const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseControlRoute = BaseControlRouteImport.update({
  id: '/base-control',
  path: '/base-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataVitalsRoute = DataVitalsRouteImport.update({
  id: '/data/vitals',
  path: '/data/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSleepRoute = DataSleepRouteImport.update({
  id: '/data/sleep',
  path: '/data/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLogsRoute = DataLogsRouteImport.update({
  id: '/data/logs',
  path: '/data/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base-control': typeof BaseControlRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/temperature': typeof TemperatureRoute
  '/water-level': typeof WaterLevelRoute
  '/data/logs': typeof DataLogsRoute
  '/data/sleep': typeof DataSleepRoute
  '/data/vitals': typeof DataVitalsRoute
  '/data': typeof DataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base-control': typeof BaseControlRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/temperature': typeof TemperatureRoute
  '/water-level': typeof WaterLevelRoute
  '/data/logs': typeof DataLogsRoute
  '/data/sleep': typeof DataSleepRoute
  '/data/vitals': typeof DataVitalsRoute
  '/data': typeof DataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base-control': typeof BaseControlRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/temperature': typeof TemperatureRoute
  '/water-level': typeof WaterLevelRoute
  '/data/logs': typeof DataLogsRoute
  '/data/sleep': typeof DataSleepRoute
  '/data/vitals': typeof DataVitalsRoute
  '/data/': typeof DataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base-control'
    | '/schedules'
    | '/settings'
    | '/temperature'
    | '/water-level'
    | '/data/logs'
    | '/data/sleep'
    | '/data/vitals'
    | '/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base-control'
    | '/schedules'
    | '/settings'
    | '/temperature'
    | '/water-level'
    | '/data/logs'
    | '/data/sleep'
    | '/data/vitals'
    | '/data'
  id:
    | '__root__'
    | '/'
    | '/base-control'
    | '/schedules'
    | '/settings'
    | '/temperature'
    | '/water-level'
    | '/data/logs'
    | '/data/sleep'
    | '/data/vitals'
    | '/data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseControlRoute: typeof BaseControlRoute
  SchedulesRoute: typeof SchedulesRoute
  SettingsRoute: typeof SettingsRoute
  TemperatureRoute: typeof TemperatureRoute
  WaterLevelRoute: typeof WaterLevelRoute
  DataLogsRoute: typeof DataLogsRoute
  DataSleepRoute: typeof DataSleepRoute
  DataVitalsRoute: typeof DataVitalsRoute
  DataIndexRoute: typeof DataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-level': {
      id: '/water-level'
      path: '/water-level'
      fullPath: '/water-level'
      preLoaderRoute: typeof WaterLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-control': {
      id: '/base-control'
      path: '/base-control'
      fullPath: '/base-control'
      preLoaderRoute: typeof BaseControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/vitals': {
      id: '/data/vitals'
      path: '/data/vitals'
      fullPath: '/data/vitals'
      preLoaderRoute: typeof DataVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/sleep': {
      id: '/data/sleep'
      path: '/data/sleep'
      fullPath: '/data/sleep'
      preLoaderRoute: typeof DataSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/logs': {
      id: '/data/logs'
      path: '/data/logs'
      fullPath: '/data/logs'
      preLoaderRoute: typeof DataLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseControlRoute: BaseControlRoute,
  SchedulesRoute: SchedulesRoute,
  SettingsRoute: SettingsRoute,
  TemperatureRoute: TemperatureRoute,
  WaterLevelRoute: WaterLevelRoute,
  DataLogsRoute: DataLogsRoute,
  DataSleepRoute: DataSleepRoute,
  DataVitalsRoute: DataVitalsRoute,
  DataIndexRoute: DataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
