"""
This script monitors a directory for the latest .RAW file generated by the 8 Sleep Pod
and processes its CBOR-encoded biometric data in real-time.

Key functionalities:
- Watches the `/persistent` directory for new .RAW files using `watchdog`.
- Tracks only the most recently modified .RAW file, avoiding stale data.
- Reads CBOR-encoded lines from the active file and extracts biometric records.
- Filters and processes `piezo-dual` sensor data, ensuring only recent entries are used.
- Loads parsed piezoelectric sensor data into `load_piezo_row` and queues it for processing.
- Uses `StreamProcessor` to analyze incoming biometric records.
- Runs the monitoring and processing loop in a separate thread for efficiency.
- Handles graceful shutdown via KeyboardInterrupt.

Usage:
This is set up to run as a systemctl service, but you can manually run it with:
/home/dac/venv/bin/python /home/dac/free-sleep/biometrics/stream/stream.py
"""

import sys
import platform
import cbor2
from datetime import datetime, timedelta
import asyncio

if platform.system().lower() == 'linux':
    sys.path.append('/home/dac/free-sleep/biometrics/')
    sys.path.append('/home/dac/free-sleep/biometrics/stream/')

import time
import os
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import queue
import threading

from get_logger import get_logger
if __name__ == '__main__':
    # Give time for the express.js server to boot.
    print('Sleeping for 30 seconds before starting stream service...')
    time.sleep(30)
logger = get_logger('free-sleep-stream')

from stream_processor import StreamProcessor
from load_raw_files import load_piezo_row
from raw_records import read_raw_record
from service_health import update_health
from nats_client import is_nats_running, load_nats_client

# Global queue for processing decoded biometric data
piezo_record_queue = queue.Queue()


# When NATS is running, we can listen directly for incoming data and send it to the legacy pipeline
async def watch_jetstream_directly():
    """Consumes CBOR metrics from JetStream and mirrors LatestRawFileHandler logic."""
    logger.info('NATS detected! Listening for sensor data in real-time...')
    update_health('stream', 'started', '')
    # Track active NATS Connection
    nc = None

    try:
        nats, nats_api = load_nats_client()
        nc = await nats.connect("nats://127.0.0.1:4222")
        js = nc.jetstream()

        # Only listen to piezo records for processing
        sub = await js.subscribe("raw.sens.piezo", stream="raw", config=nats_api.ConsumerConfig(
            deliver_policy=nats_api.DeliverPolicy.NEW
        ))

        while True:
            msg = await sub.next_msg(timeout=None)
            
            try:
                decoded_data = cbor2.loads(msg.data) 
                
                if not isinstance(decoded_data, dict) or decoded_data.get('type') != 'piezo-dual':
                    await msg.ack()
                    continue
                # Side is not used, but must be 'left' or 'right' to call
                load_piezo_row(decoded_data, 'right')
                piezo_record_queue.put(decoded_data)

            except Exception as parse_err:
                logger.error(f"Failed to process NATS/CBOR record payload: {parse_err}")

            await msg.ack()

    except asyncio.CancelledError:
        logger.info("NATS task execution cancelled.")
    except Exception as error:
        logger.error(f"NATS Stream encountered an error: {error}")
        update_health('stream', 'failed', repr(error))
        raise error
    finally:
        if nc is not None and nc.is_connected:
            await nc.close()


def _safe_getmtime(path: str) -> float:
    try:
        if os.path.exists(path):
            return os.path.getmtime(path)
    except FileNotFoundError:
        logger.warning(f'File path not found, ignoring... {path}')
        pass
    return 0  # Default for missing files


class LatestRawFileHandler(FileSystemEventHandler):
    """Monitors only the latest RAW file and processes CBOR-encoded lines separately."""

    def __init__(self, directory):
        self.directory = directory
        self.latest_file = None
        self.latest_file_obj = None
        self.last_pos = 0  # Track last read position
        self.track_latest_file()

    def track_latest_file(self):
        """Finds the most recent RAW file in the directory and starts tracking it."""
        raw_files = [f for f in os.listdir(self.directory) if f.endswith(".RAW") and not f.endswith('SEQNO.RAW')]
        if not raw_files:
            return

        # Get the latest file by modification time
        raw_files.sort(
            key=lambda f: _safe_getmtime(os.path.join(self.directory, f)),
            reverse=True
        )

        latest_file = os.path.join(self.directory, raw_files[0])

        if latest_file != self.latest_file:
            # If a new file is found, stop tracking the old one
            self.latest_file = latest_file
            logger.debug(f"Now tracking: {self.latest_file}")

            # Close old file handle if open
            if self.latest_file_obj:
                self.latest_file_obj.close()

            # Open the new file for reading in binary mode
            self.latest_file_obj = open(self.latest_file, "rb")
            self.last_pos = 0  # Reset position for new file

    def on_created(self, event):
        """Triggered when a new .RAW file is created."""
        if event.is_directory or not event.src_path.endswith(".RAW"):
            return
        self.track_latest_file()

    def follow_latest_file(self):
        """Reads and decodes new CBOR-encoded lines from the latest file."""
        if not self.latest_file_obj:
            return

        # Move to the last known position before reading
        self.latest_file_obj.seek(self.last_pos)

        while True:
            try:
                payload = read_raw_record(self.latest_file_obj)
            except EOFError:
                # Retry an incomplete wrapper after the firmware appends more bytes.
                self.latest_file_obj.seek(self.last_pos)
                break
            except Exception as error:
                logger.error(f"Error reading RAW record: {error}")
                self.latest_file_obj.seek(self.last_pos)
                break

            # Commit every complete wrapper, including skipped or malformed payloads.
            self.last_pos = self.latest_file_obj.tell()
            if payload is None:
                continue

            try:
                decoded_data = cbor2.loads(payload)
                if not isinstance(decoded_data, dict) or decoded_data.get('type') != 'piezo-dual':
                    continue
                recent_cutoff = datetime.now() - timedelta(minutes=2)
                record_time = datetime.fromtimestamp(decoded_data['ts'])
                if recent_cutoff > record_time:
                    continue
                load_piezo_row(decoded_data, 'right')
                piezo_record_queue.put(decoded_data)
            except Exception as error:
                logger.error(f"Error decoding RAW payload: {error}")


def process_biometrics():
    piezo_record = piezo_record_queue.get()
    if piezo_record is None:
        return
    stream_processor = StreamProcessor(piezo_record, debug=False)
    ix = 0
    while True:
        ix += 1
        if ix == 60:
            update_health('stream', 'healthy')
            ix = 0
        try:
            piezo_record = piezo_record_queue.get(timeout=5)

            if piezo_record is None:
                # Stop if None is received
                break

            stream_processor.process_piezo_record(piezo_record)
            piezo_record_queue.task_done()
        except queue.Empty:
            # Just continue if the queue is empty, do not exit the loop
            logger.info("No new data, retrying...")
        except Exception as error:
            logger.error(error)
            update_health('stream', 'failed', repr(error))


def watch_directory(directory="/persistent"):
    """Monitors the directory for new RAW files and processes only the latest one."""
    logger.info('Stream processor starting...')
    update_health('stream', 'started', '')
    handler = LatestRawFileHandler(directory)
    observer = Observer()
    observer.schedule(handler, directory, recursive=False)
    observer.start()

    # Start biometric processing in a separate thread
    processing_thread = threading.Thread(target=process_biometrics, daemon=True)
    processing_thread.start()

    logger.debug('Stream processor set up successfully, running...')
    try:
        while True:
            time.sleep(1)
            handler.track_latest_file()  # Check if a newer file exists
            handler.follow_latest_file()  # Read new CBOR entries line-by-line
    except KeyboardInterrupt:
        observer.stop()
        piezo_record_queue.put(None)  # Send stop signal to processing thread
        processing_thread.join()
    except Exception as error:
        logger.error(error)
        update_health('stream', 'failed', repr(error))
        raise error

    observer.join()

if __name__ == '__main__':
    # Decide whether to listen to NATS stream, or start watching and processing the latest .RAW file
    if is_nats_running():
        # Use the same legacy thread logic for processing biometrics
        processing_thread = threading.Thread(target=process_biometrics, daemon=True)
        processing_thread.start()
        try:
            asyncio.run(watch_jetstream_directly())
        except KeyboardInterrupt:
            logger.info("Stopping NATS stream processor...")
        finally:
            # Replicate legacy raw file cleanup behavior
            piezo_record_queue.put(None)
            processing_thread.join()

    else:
        try:
            watch_directory("/persistent/")
        except KeyboardInterrupt:
            logger.info("Stopping legacy stream processor...")
